// YouTube Data API client

export interface YouTubeVideoDetails {
  id: string
  title: string
  description: string
  channelId: string
  channelTitle: string
  publishedAt: string
  duration: string // ISO 8601 duration (e.g., "PT15M33S")
  thumbnails: {
    default: string
    medium: string
    high: string
    maxres?: string
  }
}

export interface YouTubeCaptionTrack {
  id: string
  language: string
  name: string
  isAutoGenerated: boolean
}

const YOUTUBE_API_BASE = 'https://www.googleapis.com/youtube/v3'

function getApiKey(): string {
  const key = process.env.YOUTUBE_API_KEY
  if (!key) {
    throw new Error('YOUTUBE_API_KEY environment variable is not set')
  }
  return key
}

// Parse ISO 8601 duration to human-readable format (e.g., "PT1H2M3S" -> "1:02:03")
export function parseDuration(isoDuration: string): string {
  const match = isoDuration.match(/PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?/)
  if (!match) return '0:00'

  const hours = parseInt(match[1] || '0', 10)
  const minutes = parseInt(match[2] || '0', 10)
  const seconds = parseInt(match[3] || '0', 10)

  if (hours > 0) {
    return `${hours}:${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}`
  }
  return `${minutes}:${seconds.toString().padStart(2, '0')}`
}

export async function getVideoDetails(videoId: string): Promise<YouTubeVideoDetails | null> {
  const apiKey = getApiKey()
  const url = `${YOUTUBE_API_BASE}/videos?` + new URLSearchParams({
    part: 'snippet,contentDetails',
    id: videoId,
    key: apiKey,
  })

  const response = await fetch(url)
  if (!response.ok) {
    console.error('YouTube API error:', response.status, await response.text())
    throw new Error(`YouTube API error: ${response.status}`)
  }

  const data = await response.json()
  if (!data.items || data.items.length === 0) {
    return null
  }

  const video = data.items[0]
  const snippet = video.snippet
  const contentDetails = video.contentDetails

  return {
    id: video.id,
    title: snippet.title,
    description: snippet.description,
    channelId: snippet.channelId,
    channelTitle: snippet.channelTitle,
    publishedAt: snippet.publishedAt,
    duration: contentDetails.duration,
    thumbnails: {
      default: snippet.thumbnails.default?.url || '',
      medium: snippet.thumbnails.medium?.url || '',
      high: snippet.thumbnails.high?.url || '',
      maxres: snippet.thumbnails.maxres?.url,
    },
  }
}

export async function getVideoCaptions(videoId: string): Promise<YouTubeCaptionTrack[]> {
  const apiKey = getApiKey()
  const url = `${YOUTUBE_API_BASE}/captions?` + new URLSearchParams({
    part: 'snippet',
    videoId: videoId,
    key: apiKey,
  })

  const response = await fetch(url)
  if (!response.ok) {
    // Caption list may not be available for all videos
    console.error('YouTube Captions API error:', response.status)
    return []
  }

  const data = await response.json()
  if (!data.items) {
    return []
  }

  return data.items.map((item: { id: string; snippet: { language: string; name: string; trackKind: string } }) => ({
    id: item.id,
    language: item.snippet.language,
    name: item.snippet.name,
    isAutoGenerated: item.snippet.trackKind === 'asr',
  }))
}

export async function getChannelInfo(channelId: string): Promise<{ id: string; title: string; customUrl: string } | null> {
  const apiKey = getApiKey()
  const url = `${YOUTUBE_API_BASE}/channels?` + new URLSearchParams({
    part: 'snippet',
    id: channelId,
    key: apiKey,
  })

  const response = await fetch(url)
  if (!response.ok) {
    console.error('YouTube Channels API error:', response.status)
    return null
  }

  const data = await response.json()
  if (!data.items || data.items.length === 0) {
    return null
  }

  const channel = data.items[0]
  return {
    id: channel.id,
    title: channel.snippet.title,
    customUrl: channel.snippet.customUrl || '',
  }
}

export async function getLatestVideos(channelId: string, maxResults: number = 10): Promise<string[]> {
  const apiKey = getApiKey()

  // First get the uploads playlist ID
  const channelUrl = `${YOUTUBE_API_BASE}/channels?` + new URLSearchParams({
    part: 'contentDetails',
    id: channelId,
    key: apiKey,
  })

  const channelResponse = await fetch(channelUrl)
  if (!channelResponse.ok) {
    throw new Error(`Failed to get channel: ${channelResponse.status}`)
  }

  const channelData = await channelResponse.json()
  if (!channelData.items || channelData.items.length === 0) {
    return []
  }

  const uploadsPlaylistId = channelData.items[0].contentDetails.relatedPlaylists.uploads

  // Get videos from the uploads playlist
  const playlistUrl = `${YOUTUBE_API_BASE}/playlistItems?` + new URLSearchParams({
    part: 'contentDetails',
    playlistId: uploadsPlaylistId,
    maxResults: maxResults.toString(),
    key: apiKey,
  })

  const playlistResponse = await fetch(playlistUrl)
  if (!playlistResponse.ok) {
    throw new Error(`Failed to get playlist: ${playlistResponse.status}`)
  }

  const playlistData = await playlistResponse.json()
  if (!playlistData.items) {
    return []
  }

  return playlistData.items.map((item: { contentDetails: { videoId: string } }) => item.contentDetails.videoId)
}
